// ============================================
// SEED DO BANCO DE DADOS - PRODUTOS REAIS
// ============================================
// Somente produtos com imagens reais geradas

import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
    console.log('🌱 Iniciando seed do banco de dados...')

    // Criar categorias
    const categories = await Promise.all([
        prisma.category.upsert({
            where: { slug: 'tenis' },
            update: {},
            create: {
                name: 'Tênis',
                slug: 'tenis',
                description: 'Tênis exclusivos e sneakers premium',
            },
        }),
    ])

    console.log('✅ Categorias criadas')

    // Produtos com imagens reais
    const products = [
        // Produtos já existentes
        {
            name: 'Nike Kobe 6 Protro Grinch',
            description: 'O icônico Kobe 6 Grinch em sua versão Protro. Colorway lendária de Natal com cabedal verde neon vibrante e detalhes em preto. Tecnologia Zoom Air para máximo conforto e performance.',
            price: 2499.90,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/kobe-6-grinch.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Verde Neon/Preto']),
            stock: 15,
            featured: true,
            isNew: true,
            onSale: false,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Force 1 Low Supreme White',
            description: 'Colaboração exclusiva entre Nike e Supreme. Air Force 1 Low em couro branco premium com o icônico box logo Supreme em vermelho.',
            price: 3299.90,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-force-1-supreme.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Branco/Vermelho']),
            stock: 8,
            featured: true,
            isNew: true,
            onSale: false,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max Plus TN Sunset',
            description: 'O lendário Air Max Plus em sua colorway Sunset. Gradiente vibrante de laranja e amarelo que remete ao pôr do sol.',
            price: 1899.90,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-tn-sunset.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Laranja/Amarelo/Preto']),
            stock: 20,
            featured: true,
            isNew: true,
            onSale: false,
            gender: 'UNISEX',
        },

        // Nike Air Max DN
        {
            name: 'Nike Air Max DN "Black Purple"',
            description: 'Nike Air Max DN em colorway Black Purple. Design inovador com sistema de amortecimento Max Air de última geração.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-air-max-dn-black-purple.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto/Roxo']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max DN "White Green"',
            description: 'Nike Air Max DN em colorway White Green. Cabedal branco com detalhes em verde vibrante.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-air-max-dn-white-green.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Branco/Verde']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },

        // Yeezy Boost 350 V2
        {
            name: 'Yeezy Boost 350 V2 "Bone"',
            description: 'Adidas Yeezy Boost 350 V2 em colorway Bone. Primeknit bege/cream com a icônica lateral listrada.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/yeezy-boost-bone.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Bone']),
            stock: 20,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Yeezy Boost 350 V2 "Citrin"',
            description: 'Adidas Yeezy Boost 350 V2 em colorway Citrin (Non-Reflective). Primeknit verde-amarelado.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/yeezy-boost-citrin.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Citrin']),
            stock: 20,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Yeezy Boost 350 V2 "Clay"',
            description: 'Adidas Yeezy Boost 350 V2 em colorway Clay. Primeknit laranja-terracota.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/yeezy-boost-clay.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Clay']),
            stock: 20,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Yeezy Boost 350 V2 "True Form"',
            description: 'Adidas Yeezy Boost 350 V2 em colorway True Form (Trfrm). Primeknit bege com sola gum.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/yeezy-boost-true-form.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['True Form']),
            stock: 20,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Yeezy Boost 350 V2 "Onyx"',
            description: 'Adidas Yeezy Boost 350 V2 em colorway Onyx. Primeknit totalmente preto com stripe tonal.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/yeezy-boost-onyx.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Onyx']),
            stock: 20,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },

        // Nike Ja 3 Morant
        {
            name: 'Nike Ja 3 Morant "Tiger"',
            description: 'Nike Ja 3 Morant Tiger Edition. Tênis de basquete com estampa de tigre vibrante.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-tiger.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Laranja/Preto']),
            stock: 15,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Ja 3 Morant "Green"',
            description: 'Nike Ja 3 Morant em Green. Tênis de basquete em verde vibrante.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-green.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Verde']),
            stock: 15,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Ja 3 Morant "Grey Lavender"',
            description: 'Nike Ja 3 Morant em Grey Lavender. Base cinza com detalhes em lavanda.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-grey-lavender.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Cinza/Lavanda']),
            stock: 15,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Ja 3 Morant "Pink"',
            description: 'Nike Ja 3 Morant em Pink. Tênis de basquete rosa vibrante.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-pink.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Rosa']),
            stock: 15,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Ja 3 Morant "Black"',
            description: 'Nike Ja 3 Morant em Black. Tênis de basquete totalmente preto.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-black.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto']),
            stock: 15,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Ja 3 Morant "Multicolor Mismatch"',
            description: 'Nike Ja 3 Morant Mismatch. Design descombinado e cores vibrantes.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-multicolor.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Multicolor']),
            stock: 10,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Ja 3 Morant "White Grey"',
            description: 'Nike Ja 3 Morant em White Grey. Design clean e moderno.',
            price: 600.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-ja-3-white-grey.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Branco/Cinza']),
            stock: 15,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },

        // Air Max 97
        {
            name: 'Nike Air Max 97 "Black"',
            description: 'Nike Air Max 97 em Black. Icônico runner dos anos 90 totalmente preto.',
            price: 430.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-97-black.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto']),
            stock: 30,
            featured: false,
            isNew: false,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max 97 "White"',
            description: 'Nike Air Max 97 em White. Cabedal branco e prata clássico.',
            price: 430.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-97-white.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Branco/Prata']),
            stock: 30,
            featured: false,
            isNew: false,
            gender: 'UNISEX',
        },

        // Bape x Crocs
        {
            name: 'Bape x Crocs Classic "Blue"',
            description: 'Colaboração Bape x Crocs em Blue. Camuflagem Bape azul com shark face.',
            price: 320.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/bape-crocs-blue.png']),
            sizes: JSON.stringify(['36', '37', '38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Azul Camo']),
            stock: 20,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Bape x Crocs Classic "Pink"',
            description: 'Colaboração Bape x Crocs em Pink. Camuflagem Bape rosa com shark face.',
            price: 320.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/bape-crocs-pink.png']),
            sizes: JSON.stringify(['36', '37', '38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Rosa Camo']),
            stock: 20,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Bape x Crocs Classic "Black"',
            description: 'Colaboração Bape x Crocs em Black. Camuflagem Bape preta com shark face.',
            price: 320.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/bape-crocs-black.png']),
            sizes: JSON.stringify(['36', '37', '38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto Camo']),
            stock: 20,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },

        // GT Cut 2
        {
            name: 'Nike GT Cut 2 "Pink/White"',
            description: 'Nike GT Cut 2 em Pink/White. Tênis de basquete de alta performance com design moderno.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/gt-cut-2-pink-white.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Rosa/Branco']),
            stock: 12,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike GT Cut 2 "Purple/Orange"',
            description: 'Nike GT Cut 2 em Purple/Orange. Tênis de basquete com design vibrante e tecnologia reativa.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/gt-cut-2-purple-orange.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Roxo/Laranja']),
            stock: 12,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },

        // Nike SB Dunk Low
        {
            name: 'Nike SB Dunk Low "Orange Bear"',
            description: 'Nike SB Dunk Low Orange Bear. Design inspirado em ursinho de pelúcia laranja.',
            price: 650.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-orange-bear.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Laranja']),
            stock: 8,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike SB Dunk Low "Green Bear"',
            description: 'Nike SB Dunk Low Green Bear. Design inspirado em ursinho de pelúcia verde.',
            price: 650.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-green-bear.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Verde']),
            stock: 8,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike SB Dunk Low "Freddy Krueger"',
            description: 'Nike SB Dunk Low Freddy Krueger. Edição temática ultra rara.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-freddy-krueger.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Vermelho/Preto']),
            stock: 5,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike SB Dunk Low "What The Dunk"',
            description: 'Nike SB Dunk Low What The Dunk. Edição especial multicolorida icônica.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-what-the-dunk.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Multicolor']),
            stock: 5,
            featured: true,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike SB Dunk Low "Nardwuar"',
            description: 'Nike SB Dunk Low Nardwuar. Colaboração exclusiva e rara.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-nardwuar.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Multicolor']),
            stock: 5,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike SB Dunk Low "Supreme 94 Green"',
            description: 'Nike SB Dunk Low Supreme 94 em Green. Colaboração Supreme clássica.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-supreme-green.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Verde']),
            stock: 5,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike SB Dunk Low "Zodiac Rattan"',
            description: 'Nike SB Dunk Low Zodiac/Rattan. Design inspirado em zodíaco.',
            price: 550.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/nike-sb-dunk-zodiac-rattan.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Bege/Marrom']),
            stock: 5,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },

        // Nike Air Max Plus
        {
            name: 'Nike Air Max Plus "Wolf Grey"',
            description: 'Nike Air Max Plus em Wolf Grey. Design clássico TN em cinza lobo.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-plus-wolf-grey.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Cinza']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max Plus "Black Metallic Silver"',
            description: 'Nike Air Max Plus em Black/Metallic Silver. Visual premium e sofisticado.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-plus-black-silver.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto/Prata']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max Plus "Triple Black"',
            description: 'Nike Air Max Plus em Triple Black. Totalmente preto monocromático.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-plus-triple-black.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max Plus "White Mica Green"',
            description: 'Nike Air Max Plus em White Mica Green. Branco com detalhes verdes.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-plus-white-mica-green.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Branco/Verde']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },
        {
            name: 'Nike Air Max Plus "Red Swoosh"',
            description: 'Nike Air Max Plus com Red Swoosh. Swoosh vermelho destacado.',
            price: 400.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/air-max-plus-red-swoosh.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto/Vermelho']),
            stock: 25,
            featured: false,
            isNew: true,
            gender: 'UNISEX',
        },

        // Adidas Samba
        {
            name: 'Adidas Samba "Black"',
            description: 'Adidas Samba clássico em Black. Tênis icônico de futebol de salão.',
            price: 320.00,
            categoryId: categories[0].id,
            images: JSON.stringify(['/images/products/tenis/adidas-samba-black.png']),
            sizes: JSON.stringify(['38', '39', '40', '41', '42', '43', '44']),
            colors: JSON.stringify(['Preto']),
            stock: 30,
            featured: false,
            isNew: false,
            gender: 'UNISEX',
        },
    ]

    for (const product of products) {
        await prisma.product.create({ data: product })
    }

    console.log('✅ Produtos criados')

    // Criar usuário de teste
    const hashedPassword = await hash('123456', 12)
    await prisma.user.upsert({
        where: { email: 'teste@supply.com' },
        update: {},
        create: {
            name: 'Usuário Teste',
            email: 'teste@supply.com',
            password: hashedPassword,
            phone: '(11) 99999-9999',
        },
    })

    console.log('✅ Usuário de teste criado (teste@supply.com / 123456)')
    console.log('🎉 Seed concluído com sucesso!')
}

main()
    .catch((e) => {
        console.error('❌ Erro no seed:', e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
